[search]
concurrency          =16
max_children_my_side =3
max_children_opp_side=3
max_total_nodes      =20000
plies                =16
rate                 =4

[policy]
cp_window    =50      # centipawns from best for engine candidates
min_play_rate=0.07    # 7%+ frequency for opponent moves
my_side      ="white" # overridden by CLI --side if provided

[quality]
base_url      ="https://lichess.org/api/cloud-eval"
cloud_multi_pv=8
multi_pv      =4                                    # how many lines to request from engine
source        ="cloud"                              # only "cloud" for now (local UCI later)

[popularity]
base_url  ="https://explorer.lichess.ovh/lichess"
max_rating=2000
min_rating=800
provider  ="explorer"
since_year=2019
speed     ="all"                                  # or "rapid", "classical", "all"
variant   ="standard"

[http]
rate_per_sec_cloud   =2
rate_per_sec_explorer=4
retries              =3
timeout_ms           =9000

[cache]
entries =200000
ttl_secs=3600

[rate]
cloud_per_sec   =2
explorer_per_sec=4
